version: '3'
services:
    redis:
      image: redis:latest
      restart: "always"
      ports:
        - 6379:6379
      volumes:
        - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
        - ./data/redis:/root/redis
      environment:
        - REDIS_PASSWORD=example
        - REDIS_PORT=6379
      command:
        - --requirepass ${REDIS_PASSWORD}
