version: '3'
services:
    redis:
      image: redis:latest
      restart: "always"
      ports:
        - 6379:6379
      volumes:
        - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
        - ./data/redis:/root/redis
      environment:
        - REDIS_PASSWORD=${REDIS_PASSWORD}
        - REDIS_PORT=${REDIS_PORT}
      command:
        - --requirepass ${REDIS_PASSWORD}
    db:
      image: postgres:latest
      restart: always
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      command:
        - -c
        - 'tcp_keepalives_idle=600'
        - -c
        - 'tcp_keepalives_interval=30'
        - -c
        - 'tcp_keepalives_count=10'
      ports:
        - 5432:5432
      volumes:
        - ./data/postgres:/var/lib/postgresql/data
    
    adminer:
      image: dpage/pgadmin4:latest
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        PGADMIN_LISTEN_PORT: 80
      ports:
      - 8080:80
      depends_on:
        - db

volumes:
  db:
    driver: local
